### ISSUE TITLE
Support GreaterThan LessThan etc for string comparisons

### ISSUE THREAD

**Issue by cherrydev** [aspnet/EntityFramework#1767]
I believe in earlier versions the expression that would, for example, generate a SQL statement of: `param > 'a' ` would be `.Where(x => String.CompareTo(x.param, "a", StringComparison.Ordinal)) > 0`. Perhaps the StringComparison.Ordinal was unnecessary and defaulted to a sane value. In EF7, the parser just punts when trying to compare strings and performs the comparison in-memory.

**Comment by maumar** [comment]
Fixed in eeb26eaea19f42320c2c00928f1be9d5aa21ae16

**Comment by toralux** [comment]
I still have issue with #1767, #3464, #5369 as the LINQ expression is evaluated locally and not on server-side as expected.

warn: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[8]
      The LINQ expression '([x].StringField.CompareTo("2000") > 0)' could not be translated and will be evaluated locally.

Running "Microsoft.EntityFrameworkCore": "1.1.0"

**Comment by rowanmiller** [comment]
@toralux please open a new issue and include a code example
