### ISSUE TITLE
QueryCompiler breaks on netnative

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3768]
Running Release mode in the UWP getting started guide results in ![image](https://cloud.githubusercontent.com/assets/2696087/11223186/88b73124-8d23-11e5-9adf-143bd03e5e76.png)

> Property 'Count' was not found on type 'System.Collections.ArrayList'.

**Comment by natemcmaster** [comment]
@rowanmiller for RC1, users will need to add this to their AppName.rd.xml file

```xml

<Type Name="System.Collections.ArrayList" Dynamic="Required All" />
```

**Comment by MMalikKhan** [comment]
Hi I am having the same issue with the .Net Native, i have this line present in the default.rd.xml 


    <Type Name="System.Collections.ArrayList" Dynamic="Required All" />

could you please suggest what i am missing ?

**Comment by divega** [comment]
@MMalikKhan are you using RC1 or RC2 bits? Most of the issues with .NET Native have been fixed for RC2 and the workarounds explained here are no longer necessary, but we require version 1.3.1 of the Universal Windows App Development Tools which are included in Visual Studio 2015 Update 2.

**Comment by MMalikKhan** [comment]
@divega  based on the @natemcmaster reply [here](https://github.com/aspnet/EntityFramework/issues/5163)
i updated the packages to Rc-2 but i am still have issue with the same line of code.. not its compiling but the error is at run time..

**Comment by ViktorBergman** [comment]
I've got the same issue here, the app is compiling but fails at runtime.
UWA Development Tools version : 1.3.2
VS: 2015 Update 2
Target platform: 10586 (x86)
Microsoft.EntityFrameworkCore.Sqlite: 1.0.0-rc2-final
Microsoft.EntityFrameworkCore.Tools: 1.0.0-preview1-final

Default.rd.xml:
< Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  < Application>
    < Assembly Name="*Application*" Dynamic="Required All" />
    
    < Type Name="System.Collections.ArrayList" Dynamic="Required All" />

  </Application>
</ Directives>

The exception occurs as soon as I'm doing .ToListAsync() on any DbSet.

**Comment by natemcmaster** [comment]
Thanks @ViktorBergman. This was reported in a few places so I opened https://github.com/aspnet/EntityFramework/issues/5517 to track this.
