### ISSUE TITLE
Repeated joins on repeated .Include().ThenInclude()

### ISSUE THREAD

**Issue by bragma** [aspnet/EntityFramework#4900]
Working with RC1

Assuming the sample schema:
DB contains Forums
Forum has many Users
Forum has many Posts
Post has many Comments

The code:
```
				var res3 = db.Users
					.Include(u => u.Forum)
					.Include(u => u.Forum)
					.ToList();
```

Generates the query:

```
SELECT [u].[UserId], [u].[ForumId], [u].[Name], [f].[ForumId], [f].[Name], [f0].[ForumId], [f0].[Name]
FROM [User] AS [u]
INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
```

While this sample may seem fake, it is less so in this case, using .ThenInclude():
```
				var res5 = db.Users.Where(u => u.Name == "user1")
					.Include(u => u.Forum).ThenInclude(f => f.Posts)
					.Include(u => u.Forum).ThenInclude(f => f.Users)
					.ToList();
```

Which generates:
```
SELECT [u].[UserId], [u].[ForumId], [u].[Name], [f].[ForumId], [f].[Name], [f0].[ForumId], [f0].[Name]
FROM [User] AS [u]
INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
WHERE [u].[Name] = 'user1'
ORDER BY [f].[ForumId], [f0].[ForumId]
```
And also:
```
SELECT [u].[UserId], [u].[ForumId], [u].[Name]
FROM [User] AS [u]
INNER JOIN (
    SELECT DISTINCT [f].[ForumId], [f0].[ForumId] AS [ForumId0]
    FROM [User] AS [u]
    INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
    INNER JOIN [Forum] AS [f0] ON [u].[ForumId] = [f0].[ForumId] <====
    WHERE [u].[Name] = 'user1'
) AS [f0] ON [u].[ForumId] = [f0].[ForumId0]
ORDER BY [f0].[ForumId], [f0].[ForumId0]
```
And then:
```
SELECT [p].[PostId], [p].[ForumId], [p].[Title]
FROM [Post] AS [p]
INNER JOIN (
    SELECT DISTINCT [f].[ForumId]
    FROM [User] AS [u]
    INNER JOIN [Forum] AS [f] ON [u].[ForumId] = [f].[ForumId]
    WHERE [u].[Name] = 'user1'
) AS [f] ON [p].[ForumId] = [f].[ForumId]
ORDER BY [f].[ForumId]
```

Is this a bug or am I doing something wrong?

**Comment by maumar** [comment]
This is a legitimate issue/limitation of EF currently

**Comment by mikes-gh** [comment]
Yes I saw this too.  Not a big fan of  ThenInclude.
It seems cumbersome to have to walk up the levels for multiple lookup tables for example and seems to lead to inefficient TSQL probably due to this.

A more fluent include system such as the mark ->  return<- concept (including filtering top request for EF6) would be fantastic.
I fear we may be stuck with this from RC2.
Will EFCore be allowed additional API rc2 -> rtm?

**Comment by maumar** [comment]
@mikes-gh we are tracking Include API improvements here https://github.com/aspnet/EntityFramework/issues/4490
API changes between RC2 and RTM will be allowed, although the bar will be higher than it is now.

**Comment by smithaitufe** [comment]
I really don't know how to use this Include and ThenInclude features of ef core.

I am trying to achieve something so simple but I can't


```
return checkOuts
            .Include(co => co.User)
            .Include(co  => co.BookVariant)
            .ThenInclude(bv => bv.Book).ThenInclude(b => b.AuthorsLink).ThenInclude(al => al.Author)
            .Include(bv => bv.Format)  
            .Include(bv => bv.Genre)          
            .Select()
```
All I want is to include book along with Format and Genre. But Book also has Authors which is linked with AuthorsLink.

But this is not working for me

**Comment by smitpatel** [comment]
@smithaitufe - The query you are looking for is this
```c#
return checkOuts
	.Include(co => co.User)
	.Include(co  => co.BookVariant)
		.ThenInclude(bv => bv.Book).ThenInclude(b => b.AuthorsLink).ThenInclude(al => al.Author)
	.Include(co  => co.BookVariant)
		.ThenInclude(bv => bv.Format)  
	.Include(co  => co.BookVariant)
		.ThenInclude(bv => bv.Genre)          
	.Select()
```
`Include` always starts at the base entity (which is checkout here) If you want to include multiple navigations after including BookVariant, you need to repeat include on BookVariant each time.

**Comment by smithaitufe** [comment]
@smitpatel Thanks so much. I have read through the doc many times but I was not patient enough to see the details.
I came up with something like this.

```
var checkOutQuery = checkOuts
            .Include(co => co.User)
            .Include(co => co.BookVariant)
            .ThenInclude(bv => bv.Book).ThenInclude(b => b.AuthorsLink).ThenInclude(al => al.Author)
            .Include(co => co.BookVariant)
            .ThenInclude(bv => bv.Format)
            .Include(co => co.BookVariant).ThenInclude(bv => bv.Book).ThenInclude(bv => bv.Genre);
```
Any idea about the performance of this multiple include?

**Comment by anpete** [comment]
Fixed by new Include compiler.

**Comment by divega** [comment]
@anpete should this be marked as fixed in 2.0.0-preview1 or 2.0.0?

**Comment by anpete** [comment]
@divega Preview 1!

**Comment by fkhasib** [comment]
I am still facing this issue on 2.0.0, I end up with multiple repeated records for the same entity if I use multiple Include and ThenInclude. Is this suppose to be fixed with 2.0.0-preview-1 but not 2.0.0?
