### ISSUE TITLE
dotnet ef migrations list  problem

### ISSUE THREAD

**Issue by antonioapostoliu** [aspnet/EntityFramework#5281]
dotnet ef migrations list 
give me:
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Runtime()'.
   at Microsoft.EntityFrameworkCore.Commands.ReflectionOperationExecutor..ctor(String startupProject, String environment)
   at Microsoft.EntityFrameworkCore.Commands.MigrationsListCommand.Execute(String context, String startupProject, String environment, Action`1 reportResultsAction)
   at Microsoft.EntityFrameworkCore.Commands.MigrationsListCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Commands.Program.Main(String[] args)
Method not found: 'Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Runtime()'.

All because of:
https://github.com/aspnet/PlatformAbstractions/commit/95d352a1886ea53bab837714e0a47272657087a5

Please modify the code for accomodate this two day old commit.

Best regards

**Comment by rowanmiller** [comment]
@natemcmaster did we already have a change in the pipeline to react to this?

**Comment by natemcmaster** [comment]
Yes. @antonioapostoliu can you share which version of Entity Framework packages you have installed? (project.lock.json). This should have already been fixed in builds >= 20832

**Comment by antonioapostoliu** [comment]
Error persist today
===================================================
D:\fix4\MusicStore-dev\src\MusicStore>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002700)

Product Information:
 Version:     1.0.0-preview1-002700
 Commit Sha:  0336f6bb34

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86
====================================================
D:\fix4\MusicStore-dev\src\MusicStore>cat project.json
{
  "authors": [
    "Microsoft"
  ],
  "description": "Music store application on ASP.NET 5",
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true,
    "define": [
      "DEMO",
      "TESTING"
    ],
 "compile": {
        "include": [ "../../shared/**/*.cs" ],
    "preserveCompilationContext": true
  }
},
  "commands": {
    "web": "MusicStore"
  },
  "publishOptions": {
    "include": [
      "Areas",
      "Views",
      "wwwroot",
      "config.json",
      "web.config" ],
    "exclude": [ ],
    "includeFiles": [ ],
    "excludeFiles": [ ],
    "builtIns": [ ],
    "mappings": {
      "dest/path": "./src/path"
    }
  },
  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.MicrosoftAccount": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Twitter": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-*",
    "Microsoft.AspNetCore.Session": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.InMemory": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-*",
    "Microsoft.NETCore.Platforms": "1.0.1-*",
"Microsoft.EntityFrameworkCore.Tools.Cli": "1.0.0-*",
"Microsoft.EntityFrameworkCore.Commands": "1.0.0-*",
"Microsoft.EntityFrameworkCore.Relational": "1.0.0-*",
"Microsoft.EntityFrameworkCore.Relational.Design": "1.0.0-*",
"Microsoft.Extensions.PlatformAbstractions": "1.0.0-*"
  },
  "frameworks": {
    "net451": {},
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      },
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
  },
  "tools": {
"dotnet-ef": {
       "version": "1.0.0-*",
       "imports": [ "dnxcore50", "portable-net452+win81" ]
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
}
=========================================
D:\fix4\MusicStore-dev>cat NuGet.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
<clear/>
    <add key="AspNetVNext" value="https://www.myget.org/F/aspnetcidev/api/v3/index.json" />
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
================================
Before use each new dev version I erase 
 C:\Users\Implozia\.nuget\packages
 C:\Users\Implozia\AppData\Local\NuGet\v3-cache
Also in Control panel I have after filter with core word only 
Microsoft.NET Core 1.0.0 RC2 - Runtime (x86)
Microsoft.NET Core 1.0.0 RC2 - SDK Preview 1 (x86)
Please tell me if I need to erase other folders before use dotnet restore with newer dev versions

Best Regards
===============================

**Comment by antonioapostoliu** [comment]
I don't wanted to write with different font weights and size. I don't know what github input filter does it.
Best Regards

**Comment by antonioapostoliu** [comment]
From project.lock.json:

"Microsoft.EntityFrameworkCore.Commands/1.0.0-rc3-20680": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Hosting.Abstractions": "1.0.0-rc3-20680",
          "Microsoft.EntityFrameworkCore.Relational.Design": "1.0.0-rc3-20680",
          "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc3-20680",
          "System.Collections.NonGeneric": "4.0.1-rc2-24018",
          "System.IO": "4.1.0-rc2-24018",
          "System.IO.FileSystem": "4.0.1-rc2-24018"
        },
I will add 1.0.0-rc3-20832

**Comment by antonioapostoliu** [comment]
I added 1.0.0-rc3-20832 only for Microsoft.EntityFrameworkCore.Commands 
dot net restore give me:
Errors in D:\fix4\MusicStore-dev\src\MusicStore\project.json
    Unable to resolve 'Microsoft.EntityFrameworkCore.Commands (>= 1.0.0-rc3-20832)' for '.NETFramework,Version=v4.5.1'.
    Unable to resolve 'Microsoft.EntityFrameworkCore.Commands (>= 1.0.0-rc3-20832)' for '.NETCoreApp,Version=v1.0'.

NuGet Config files used:
    D:\fix4\MusicStore-dev\NuGet.Config
    C:\Users\Implozia\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetcidev/api/v3/index.json
    https://api.nuget.org/v3/index.json

**Comment by natemcmaster** [comment]
@antonioapostoliu the packages you are using are obsolete. We merged Microsoft.EntityFrameworkCore.Commands and dotnet-ef into one package named "Microsoft.EntityFrameworkCore.Tools". Can you update to these new packages and let us know if your bug still reproduces?

**Comment by antonioapostoliu** [comment]
I try this:
"Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.MicrosoftAccount": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Twitter": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-*",
    "Microsoft.AspNetCore.Session": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-*",
    "Microsoft.NETCore.Platforms": "1.0.1-*",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
"Microsoft.EntityFrameworkCore.InMemory": "1.0.0-*",
"Microsoft.Extensions.PlatformAbstractions": "1.0.0-*"
===============================================
same migrations list error ...
=================================================

from  project.lock.json :

      "Microsoft.EntityFrameworkCore.Tools/1.0.0-rc3-20833": {
        "type": "package",
        "dependencies": {
          "Microsoft.AspNetCore.Hosting.Abstractions": "1.0.0-rc3-20833",
          "Microsoft.EntityFrameworkCore.Tools.Cli": "1.0.0-rc3-20833",
          "Microsoft.EntityFrameworkCore.Tools.Core": "1.0.0-rc3-20833",
          "Microsoft.Extensions.PlatformAbstractions": "1.0.0-rc3-20833",
          "Microsoft.NETCore.App": "1.0.0-rc2-3002611"
        },
        "compile": {
          "lib/netcoreapp1.0/dotnet-ef.dll": {}
        },
        "runtime": {
          "lib/netcoreapp1.0/dotnet-ef.dll": {}
        }
      },

**Comment by antonioapostoliu** [comment]
Again I don't know why github import filter change the font...

**Comment by antonioapostoliu** [comment]
I figure what was with fonts in my comments....I used lines with twenty equal sign between paragraphs. Github use mark it escape sequence of characters to format rich text islands of text. Appologies mister ...

**Comment by cevarief** [comment]
What is the proper version and import for preview1 [1.0.0-preview1-002702] ?

```json
"tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-*",
      "imports": "portable-net452+win81"
    },
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-preview1-*",
      "imports": "portable-net452+win81"
    }
```
dotnet ef throws error :
```bash
System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Runtime()'.
   at Microsoft.DotNet.Cli.Utils.DefaultCommandResolverPolicy.Create()
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.EntityFrameworkCore.Tools.DispatchCommand.<>c__DisplayClass2_0.<Create>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Method not found: 'Microsoft.Extensions.PlatformAbstractions.IRuntimeEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Runtime()'.
```

**Comment by antonioapostoliu** [comment]
Today situation:
D:\fix4\MusicStore-dev\src\MusicStore>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86
D:\fix4\MusicStore-dev\src\MusicStore>cat project.json
{
  "authors": [
    "Microsoft"
  ],
  "description": "Music store application on ASP.NET 5",
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "warningsAsErrors": true,
    "define": [
      "DEMO",
      "TESTING"
    ],
 "compile": {
        "include": [ "../../shared/**/*.cs" ],
    "preserveCompilationContext": true
  }
},
  "commands": {
    "web": "MusicStore"
  },

  "publishOptions": {
    "include": [
      "Areas",
      "Views",
      "wwwroot",
      "config.json",
      "web.config" ],
    "exclude": [ ],
    "includeFiles": [ ],
    "excludeFiles": [ ],
    "builtIns": [ ],
    "mappings": {
      "dest/path": "./src/path"
    }
  },

  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.MicrosoftAccount": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0-*",
    "Microsoft.AspNetCore.Authentication.Twitter": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-*",
    "Microsoft.AspNetCore.Session": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-*",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-*",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-*",
    "Microsoft.NETCore.Platforms": "1.0.1-*",
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-*",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
"Microsoft.EntityFrameworkCore.InMemory": "1.0.0-*",
"Microsoft.Extensions.PlatformAbstractions": "1.0.0-*"
  },
  "frameworks": {
    "net451": {},
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      },
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
  },
  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview1-*",
      "imports": "portable-net452+win81"
    },
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-preview1-*",
      "imports": "portable-net452+win81"
    },
     "dotnet-ef": {
       "version": "1.0.0-*",
       "imports": [ "dnxcore50", "portable-net452+win81" ]
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
}

D:\fix4\MusicStore-dev\src\MusicStore>dotnet build
Project MusicStore (.NETFramework,Version=v4.5.1) will be compiled because inputs were modified
Compiling MusicStore for .NETFramework,Version=v4.5.1
D:\fix4\MusicStore-dev\src\MusicStore\project.json(65,58): warning NU1007: Dependency specified was Microsoft.EntityFrameworkCore.Tools >= 1.0.0-preview1-* but ended up with Microsoft.EntityFrameworkCore.Tools 1.0.0-rc3-20826.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:03.2081356


Project MusicStore (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling MusicStore for .NETCoreApp,Version=v1.0
D:\fix4\MusicStore-dev\src\MusicStore\project.json(65,58): warning NU1007: Dependency specified was Microsoft.EntityFrameworkCore.Tools >= 1.0.0-preview1-* but ended up with Microsoft.EntityFrameworkCore.Tools 1.0.0-rc3-20826.

Compilation succeeded.
    1 Warning(s)
    0 Error(s)

Time elapsed 00:00:02.3149931

D:\fix4\MusicStore-dev\src\MusicStore>dotnet run
Project MusicStore (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Hosting environment: Production
Content root path: D:\fix4\MusicStore-dev\src\MusicStore\bin\Debug\netcoreapp1.0
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
^C
D:\fix4\MusicStore-dev\src\MusicStore>dotnet ef migrations list
Project MusicStore (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
No migrations were found

Pretty good.
If I will can find and erase Microsoft.EntityFrameworkCore.Tools 1.0.0-rc3-20826 all will work without build warnings.

Best regards.

**Comment by antonioapostoliu** [comment]
I delete 
C:\Users\Implozia\nuget\packages
C:\Users\Implozia\AppData\Local\NuGet\v3-cache
D:\fix4\MusicStore-dev\src\MusicStore\bin\Debug
D:\fix4\MusicStore-dev\src\MusicStore\obj\Debug

dotnet restore works ok 
I have little problem with:

D:\fix4\MusicStore-dev\src\MusicStore>dotnet run
Project MusicStore (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'config.json' was not found and is not optional.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MusicStore.Startup..ctor(IHostingEnvironment hostingEnvironment)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetServiceOrCreateInstance(IServiceProvider provider, Type type)
   at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider services, Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass13_1.<BuildHostingServices>b__1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.SingletonCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at MusicStore.Program.Main(String[] args)

D:\fix4\MusicStore-dev\src\MusicStore>cat config.json
ï»¿{
  "AppSettings": {
    "SiteTitle": "ASP.NET MVC Music Store",
    "CacheDbResults": true
  },
  "DefaultAdminUsername": "Administrator@test.com",
  "DefaultAdminPassword": "YouShouldChangeThisPassword1!",
  "Data": {
    "DefaultConnection": {
      // Use a shared (and running) LocalDB database when executing in IIS e.g.
      // "Server=(localdb)\\.\\IIS_DB;Database=MusicStore;Trusted_Connection=False;MultipleActiveResultSets=true;User ID=iis_login;Password=********"
      "ConnectionString": "Server=(localdb)\\MSSQLLocalDB;Database=MusicStore;Trusted_Connection=True;MultipleActiveResultSets=true;Connect Timeout=30;"
    }
  }
}
D:\fix4\MusicStore-dev\src\MusicStore>

**Comment by natemcmaster** [comment]
@antonioapostoliu my guess is the package of Microsoft.DotNet.Cli.Utils you are using is old. We are still sorting out issues with our nightly feeds recently. We decided to name our tools packages "preview1" instead of "rc2". NuGet thinks "preview1" is older than "rc2" (alphabetical). We're still trying to track down all the places where we need to delete "rc2" from our feeds.

cc @pranavkm

**Comment by natemcmaster** [comment]
Work on this is being tracked https://github.com/dotnet/cli/issues/3012

**Comment by pranavkm** [comment]
Working with @Eilon and @victorhurdugaci  to determine if we could drop the ci[dev|release] feeds and rebuild them from latest coherence.

**Comment by Eilon** [comment]
Yeah we will clean up the feeds.

**Comment by antonioapostoliu** [comment]
Today  2016 may 19 situation:
D:\fix_rc2\rc2\src\MusicStore>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86

D:\fix_rc2\rc2\src\MusicStore>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x86

D:\fix_rc2\rc2\src\MusicStore>cat project.json
{
  "authors": ["Microsoft"],
  "description": "Music store application on ASP.NET 5","version": "1.0.0-*",
  "buildOptions": { "compile": {"include": ["../../shared/**/*.cs"]},
  "copyToOutput": {
                "include": ["Areas","Views","wwwroot","config.json","web.config"]
    },
    "define": ["DEMO","TESTING"],"emitEntryPoint": true,
    "preserveCompilationContext": true,"warningsAsErrors": true
  },
"publishOptions": {
                "include": ["Areas","Views","wwwroot","config.json","web.config"]
  },
  "dependencies": {
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Facebook": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.MicrosoftAccount": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Twitter": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.WebListener": "0.1.0-rc2-final",
    "Microsoft.AspNetCore.Session": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.InMemory": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview1-final",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Relational": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Relational.Design": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Cors": "1.0.0-rc2-final",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0-rc2-final"
  },
  "frameworks": { "net451": {},
    "netcoreapp1.0": {
      "dependencies": {
"Microsoft.NETCore.App": {"version": "1.0.0-rc2-3002702","type": "platform"}},
      "imports": ["dnxcore50","portable-net451+win8"]
    }
  },
  "tools": {
   "Microsoft.EntityFrameworkCore.Tools": {
    "version": "1.0.0-preview1-final",
    "imports": ["portable-net45+win8+dnxcore50","portable-net45+win8"]
   },
   "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*","imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
   }
  },
  "scripts": { "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
}

dotnet restore works ok.
dotnet build works ok
dotnet run works ok
dotnet ef migrations list works ok
D:\fix_rc2\rc2\src\MusicStore>dotnet ef migrations list
Project MusicStore (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
No migrations were found
D:\fix_rc2\rc2\src\MusicStore>

All is ok.
Thank you!
Best regards
