### ISSUE TITLE
Include closes connection affecting ongoing transaction

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#5628]
_From @vmlf01 on Feb 4, 2016, 20:16_

When running a query with an .Include() clause, if the main table does not return any records, the connection seems to close, which will affect ongoing transaction.

```
                using (var tx = CTX.Database.BeginTransaction(System.Data.IsolationLevel.Serializable))
                {
                    // this call which won't match any results for DbValues
                    // closes the connection and causes the tx.Commit() to throw an error
                    var t = await CTX.DbValues
                        .Include(v => v.Details)
                        .Where(v => v.Id == "AAAAAAAA")
                        .ToListAsync();

                    result = t.Select(v => v.Value);

                    // this will throw
                    tx.Commit();
                }
```

```
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "v"."Id", "v"."Value"
      FROM "Values" AS "v"
      WHERE "v"."Id" = 'AAAAAAAA'
      ORDER BY "v"."Id"
fail: Microsoft.AspNet.Server.Kestrel[13]
      An unhandled exception was thrown by the application.
      System.InvalidOperationException: This SqliteTransaction has completed; it is no longer usable.
         at Microsoft.Data.Sqlite.SqliteTransaction.Commit()
         at Microsoft.Data.Entity.Storage.RelationalTransaction.Commit()
         at WebApplication1.Controllers.ValuesController.<Get>d__2.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__42.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__33.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<InvokeActionAsync>d__8.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.IISPlatformHandler.IISPlatformHandlerMiddleware.<Invoke>d__4.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Server.Kestrel.Http.Frame`1.<RequestProcessingAsync>d__3.MoveNext()
info: Microsoft.AspNet.Hosting.Internal.WebApplication[2]
```
I have attached a simple webapi project that reproduces the problem, you just have to hit http://localhost:5000/api/values.

I'm running on Win7 1.0.0-rc2-16357 coreclr x64, but same thing happens on ubuntu with same runtime.

[WebApplication1.zip](https://github.com/aspnet/Microsoft.Data.Sqlite/files/118161/WebApplication1.zip)

_Copied from original issue: aspnet/Microsoft.Data.Sqlite#224_

**Comment by bricelam** [comment]
@mikary might have some insight.

**Comment by bricelam** [comment]
_From @natemcmaster on Feb 4, 2016, 23:16_

Could this be the same issue serializable bug we fixed in aspnet/Microsoft.Data.Sqlite#213 ?

**Comment by mikary** [comment]
@bricelam This does appear to reproduce with RC2 final and only when include is used in the sync case as well. I would expect the connection to still be open (even after the transaction is disposed) and the query should only be updating reference counts on the `RelationalConnection` and using the transaction passively (automatically used by `RelatoinalCommand`)

@maumar Does `Include` do any special connection management when sending commands? My suspicion would be that this relates to `QueryingEnumerable` and managing non-MARS queries.

**Comment by smitpatel** [comment]
The issue persists for SqlServer also. MARS - true/false both.
The issue is in counting of connection while doing `Include`.
When we have `Include` (also `ThenInclude`) in the query then we open the connection only once. (openedcount++) but all the relatedEntitiesLoaders will close the connection while disposing.
That means we close the connection more times than we open so any user opened connection are closed in the process.
