### ISSUE TITLE
UWP Commands: unhelpful error when executing on a UWP class library

### ISSUE THREAD

**Issue by davesmits** [aspnet/EntityFramework#5878]
One of my apps i was trying to upgrade from RC1 to RTM i hit a issue with a refence not set to an instance error when running "Add-Migration". I start to make a new project with the same structure to figure out what is going on, but before i was able to come to that state hitting another issue:

When doing "Add-Migration InitialDB" I get this exception:
Add-Migration : Exception calling "CreateInstanceAndUnwrap" with "8" argument(s): "Could not load file or assembly 'Microsoft.EntityFrameworkCore.Design.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its 
dependencies. The system cannot find the file specified."
At line:1 char:1
+ Add-Migration initialdb
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Migration], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException,Add-Migration
 
I added a repro project. You need to set the EFTest.Model as startup project and default project
[EFTest.zip](https://github.com/aspnet/EntityFramework/files/335757/EFTest.zip)

**Comment by natemcmaster** [comment]
Confirmed this is an issue. It happens when a UWP class library project is marked as the "startup" project. MSBuild for UWP csproj does not copy dependencies into build target dir (bin/) so the powershell commands cannot execute.

**Workaround**

Set the UWP **app** as the Startup project (right click on project > Set as StartUp project) or use the `-StartupProject` option in PMC.

**Comment by SamuelLioult** [comment]
@natemcmaster this workaround doesn't work for me. I think it is because my data part is in this library. So when I try to run the command line with the UWP app as startup project, I get this error:

> Cannot execute this command because Microsoft.EntityFrameworkCore.Tools is not installed in the startup project 'UWPProject'.

**Comment by natemcmaster** [comment]
@SamuelLioult you will need to install Microsoft.EntityFrameworkCore.Tools into the startup project, not the class library project.

**Comment by SamuelLioult** [comment]
@natemcmaster I tried it but I get the error reported here #5471 but it works with the app.config as in the proposed workaround.

**Comment by bartlannoeye** [comment]
For future reference: I had the reported issue while trying to add migrations with the AnyCPU configuration selected (which happened to be default on opening the project and doesn't build the UWP app). Swithing to x86 fixed it.

**Comment by bricelam** [comment]
@bartlannoeye In the next release (1.0.0-preview3), you'll be able to have any of AnyCPU, x64, or x86 selected.

**Comment by yehe01** [comment]
Hi,
I am having this issue on a console application. The issue only exist on EntityFrameworkCore but not EntityFramewokr6.x.

![capture](https://cloud.githubusercontent.com/assets/1256556/19754202/23d2162c-9c57-11e6-9640-bb3bb601494e.PNG)

**Comment by yehe01** [comment]
Issue solved by creating a clean project. Also, the [tutorial](https://docs.efproject.net/en/latest/platforms/full-dotnet/new-db.html) doesn't mention to install `Microsoft.EntityFrameworkCore.Design`, but it's apparently needed.

**Comment by bartlannoeye** [comment]
And this error is back on UWP with the latest tools (1.1.0-preview4-final). Our client's patient is getting really thin by the continued delays caused by EF Core. It's sad to see these tools are so fragile and lack a correct guide to follow.
