### ISSUE TITLE
.NET Native: optimize code + native toolchain causes runtime exceptions

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#6253]
## Scenario

Compiling a UWP app with both the .NET Native toolchain and code optimizer can cause runtime errors for apps using EF Core 1.0.0. This issue appears most on ARM devices, and are manifest in a variety of runtime exceptions.
## Workaround

Opt-out of the code optimizer. As suggested in a few places (https://github.com/Azure/azure-mobile-services/issues/890#issuecomment-230610187 and https://github.com/aspnet/EntityFramework/issues/6027#issuecomment-237884929), runtime directives (rd.xml) can be used to exclude parts of code from the optimizer by adding the `DoNotOptimize="true" DoNotInline="true"` properties.

Example:

``` xml
<Assembly Name="SomeAssemblyNameWithoutExtension" DoNotOptimize="true" DoNotInline="true" />
```

The .NET Native team is currently investigating a fix. TFS #248588

cc @DamirLisak @ViktorBergman  @nicojmb @mattwhilden

For triage: we could consider adding the DoNotOptimize="true" property into our rd.xml files, but before we do we should investigate the perf implications.

**Comment by RonFrick** [comment]
The optimizer workaround does work, but makes the app very slow for even simple queries. 
Anyone have tips on this? I really can't release our app until this works as expected.

**Comment by RonFrick** [comment]
Can we use an older version of EF core?

**Comment by ErikEJ** [comment]
Have you tried using sqlite-net instead?

**Comment by RonFrick** [comment]
Well I guess I have no other choice with a pending deadline. :) Thanks for the suggestion. I just wish there was some way to push to the store without having the optimizer run. It runs great on a debug build, but is almost unusable on release builds.

**Comment by RonFrick** [comment]
I will look at this when I have more time. Thank you for the suggestion!!
I was hoping I could simply exclude the ARM release build from using the .net toolchain when building the upload package.

**Comment by RonFrick** [comment]
Ok, so I have months worth of work in EF so making the switch to SQLite-net is something I will face only if the fix for this is months away? Does anyone have thoughts on when we can put the optimizer back in place for EF on ARM?

**Comment by ErikEJ** [comment]
Wau, that sounds like a huge app!

**Comment by RonFrick** [comment]
It is a LOB app, that involves EF, MS Sync framework, and AutoRest...Not to mention it uses a receipt printer, barcode scanner, and a MSR. Got the whole kitchen sink involved to get data moved around. :) I wish I would have seen the SQLite-net when I started, it's looks really nice and simple. :) Guess we will put up with a side-load until everything gets worked out. Thanks again for the suggestion.

**Comment by ErikEJ** [comment]
Maybe the UWP platform is not ready for big LOB apps yet?

**Comment by RonFrick** [comment]
I would have to agree with you on that at this point, and certainly not on ARM processors. Are there only a handful of us using EF on ARM?

**Comment by RonFrick** [comment]
Just have to go back to windows mobile 6.5. :)

**Comment by jspuij** [comment]
Sadly, I'll chime in with you on UWP not being ready. We're in the same boat with a serious LOB app that uses EF, Reactive UI, Automapper and Sharepoint CSOM. It was basically ready 6 weeks ago in debug, but we've been chasing .NET native AOT bugs (and UWP bugs) ever since. It's more or less in a usable state now, but in .NET native mode it's by far slower than in JITted form in debug mode, even on the device.

Now in hindsight, it probably wasn't smart to use 3 technologies (EF Core / Linq, Reactive UI, Automapper) that rely heavily on reflection (and Reflection.Emit / Expression.Compile) on a platform like UWP but coming from the full .NET framework I've got a feeling that we stepped back into the dark ages and have thrown the baby out with the bathwater. 

The assumption that JITted code is slow and unsafe and therefore be banned from UWP apps might be a fair one, but then be consistent with it and abandon reflection and everything that depends on runtime code generation altogether. However now with the half baked solution of interpreting expression trees and using runtime directives to control RTTI it has become a big slow unstable mess.

More worryingly you only are going to find out about these problems when you run your application in release mode, something you desperately try to avoid during development because of the abysmal performance of the .NET native compiler toolchain (5GB memory usage over a few 32bit processes, 30+ minute compile times and regular OOM's).

The only bright side I see is that the customer considers switching to iOS or Android devices because of dropping market share of Window mobile 10 and the lack of announced devices from MS. With Xamarin and our final architecture I think we're in a good position to switch to iOS and Android easily, now that we've eliminated most of the AOT gotchas that probably would bite us on those platforms as well.

It's irony I guess that JIT in the javascript world is gaining traction with V8 and Chakra and on the other side is completely abandoned in the .NET world. I thought it were exiting times because finally power of expression and development speed (closures, higher order functions, Linq, whatever) were available with reasonable runtime performance because of JIT compilation. I guess I was wrong.

**Comment by RonFrick** [comment]
Hard pill to swallow at this point. I sadly agree. Does anyone have suggestions on specific runtime directives?  This catch all seems to be the only thing that works. Performance takes a huge hit...
<Assembly Name="*Application*" Dynamic="Required All" DoNotOptimize="true"  DoNotInline="true"/>

**Comment by ViktorBergman** [comment]
Interesting comment by @jspuij . 
I fully agree that .NET Native + EF Core hasn't delivered on it's promise. Countless hours has been spent on chasing issues related to the native compiler not to mention the hours spent actually compiling. 
Having said that I have not lost faith in UWP especially since the teams are doing an excellent job in communicating and fixing said issues.

However I would really appreciate a comment from the team on @jspuijs point of view. @natemcmaster @divega

**Comment by MattWhilden** [comment]
I've been digging through the repro provided over in #6027 and now have a much better understanding of the issue. You can see my comments over there, which include a workaround that is much more targeted. For anyone who has seen issues working on ARM, I'd greatly appreciate it if you could try it out and let me know. In particular, I'd like to know if the more targeted workaround is still performance crippling or not. We have a few more tools in the tool belt but don't want to suggest more gymnastics if it's not necessary.

There may be more issues lurking so please ping me directly if you find that to be the case. As always, for .NET Native realted feedback please send info to me here or at dotnetnative@microsoft.com. ex: I'd love to know more about your project @jspuij, 30+minute compiles are absolutely bugs I'd love to chase down!

**Comment by RonFrick** [comment]
Absolutely, thanks for the help. I will let you know asap.

**Comment by jspuij** [comment]
@MattWhilden The project actually isn't that big, it just uses EF Core, Reactive UI, Automapper, Sharepoint  portable CSOM library. It has roughly 30 Pages / User controls, 30 viewmodels and 15 Entities. It uses SQLite for local storage on the device and the sharepoint CSOM library to sync data with Sharepoint.

Compiling x86 in release takes around 7 minutes, compiling x64 seems a good bit slower, ARM is somewhere in between. Switching from debug to release (and vice versa) makes the XAML compiler throw up, so you have to do a complete clean and rebuild afterwards, which takes around 30 minutes to compile.

**Comment by MattWhilden** [comment]
Yikes! I'd be happy to take a closer look to see what can be done. Fortunately, there's a pretty easy way for you to ship us enough artifacts to do an investigation. If that's something of interest can you send me a mail at dotnetnative@microsoft.com? 

The relevant collection steps are outlined in the first part here: https://github.com/dotnet/core/blob/master/Documentation/ilcRepro.md

**Comment by jspuij** [comment]
@MattWhilden it seems that i've missed an issue with automapper that explains my build times, no need to investigate any further. Sorry for the trouble. For future reference, it's:
https://github.com/AutoMapper/AutoMapper/issues/1655

**Comment by MattWhilden** [comment]
Out of curiosity what is your build time with that workaround?

**Comment by jspuij** [comment]
@MattWhilden It's a little better but still many minutes. I've sent you the ilcrepro file.

**Comment by MattWhilden** [comment]
To follow up on this. So there's a number of interesting patterns that cause @jspuij's app to take a while to build. One my machine it takes about 3.5 minutes to build. As an experiment, I can get that down to ~2 minutes if I do a bit of rather unsavory hacking which I think is the absolute best we can currently do with the way our tools are structured. The hacking comes with a bunch of runtime failures (aka the app crashes now) so it's not something that I'm comfortable even recommending you try.

All that said, we've been working on various architecture level changes that can greatly help with these kinds of cases. If you don't mind me clinging to this repro pack for a bit longer, I'd love to keep using it as part of our larger battery of assets we use to assess how those efforts are panning out.

I really appreciate you taking the time to send this in... Unfortunately, there's no silver bullet here.

**Comment by jspuij** [comment]
@MattWhilden Thank you for the follow up. That's about what I see now as well, multiply that by 3 for all architectures and indeed it's about 10 to 15 minutes now for a test release. (as we've experienced differences between ARM and x86, we test all now). I don't mind you holding on to the repro a bit longer.

I don't mean to side rail the issue at hand, but out of curiosity: With the acquisition of Xamarin, you now seem to have 3 AOT compilers for .NET: the UWP version, the mono LLVM compiler and the .NET Core llilc compiler. You speak of architecture level changes, does this mean integrating a few or will these continue to co-exist?

**Comment by MattWhilden** [comment]
More like, what things do we need to change if we want to make order of magnitude improvements to compiler thoughput (read: build time). While we've done work targeted at making builds faster, build time has traditionally been a thing we've been okay trading off for other optimization features. It's become more and more apparent that we'll need to do something "big" to close the gap between native and non-native build times. Meaning, that making 2% improvements across many components just isn't going to end up being enough. Many of our bigger ideas will require reorganizations of the various components/phases of the compiler. Anyhow, not much to share except that we definitely recognize the pain.

As always, thanks for working with us as we work through these things.

**Comment by DamirLisak** [comment]
Hi,
Can somebody inform us (developers) about the state of fixing this issue (TFS #248588)?
When will Microsoft roll out a new VS/Compiler-Update?
(@MattWhilden , @natemcmaster)

**Comment by MattWhilden** [comment]
@DamirLisak The .NET Native tools shipping cadence is aligned with Visual Studio. The fix for this issue will be included with Visual Studio '15'.

**Comment by DamirLisak** [comment]
Information for other developers:
The latest compiler in „Visual Studio ‚15‘ Preview 5“  doesn’t include the fix. I have tested it with my project.

Von: Matthew Whilden [mailto:notifications@github.com]
Gesendet: Freitag, 28. Oktober 2016 01:48
An: aspnet/EntityFramework <EntityFramework@noreply.github.com>
Cc: Damir Lisak <damir.lisak@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [aspnet/EntityFramework] .NET Native: optimize code + native toolchain causes runtime exceptions (#6253)


@DamirLisak<https://github.com/DamirLisak> The .NET Native tools shipping cadence is aligned with Visual Studio. The fix for this issue will be included with Visual Studio '15'.

**Comment by MMalikKhan** [comment]
@DamirLisak, @natemcmaster @MattWhilden @jspuij  do you have any idea if this is fixed in the Visual Studio 2017 RC ? I am having the same issue if i turn off optimization then i see other null exceptions from different part of the solution. And the worst is the package size is increased x 6 times.  any help is much appreciated. 

Note: I am using EF 1 Core in my solution.

Thank You

**Comment by DamirLisak** [comment]
Hi Malik,

I don’t know this.
I currently use the following versions of EF-Core:
    "Microsoft.Data.Sqlite": "1.0.0-rc2-final",
    "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-rc2-final",
An this is the only one version which works with the native toolchain!

All other versions are not working.
Also it doesn’t work on ARM-Processors if you exclude the three assemblies in the Default.rd.xml as Nate has suggested:
    <Assembly Name="Microsoft.EntityFrameworkCore.Sqlite" DoNotOptimize="true" DoNotInline="true" />
    <Assembly Name="Microsoft.EntityFrameworkCore" DoNotOptimize="true" DoNotInline="true" />
    <Assembly Name="Microsoft.EntityFrameworkCore.Relational" DoNotOptimize="true" DoNotInline="true" />
I have tried this with all newer EF-Core-Versions.

I hope the Roslyn-Team will fixed it soon.
I give you another advice: Please test your Application by sideloading your App-Package to a ARM-Device before you deploy it to the store. I had some effects which you don’t have when you only debug in Release-Mode, because the Packager has also bugs. Here I hope also, that Mircosoft will do some better work, so that we developers don’t have to test our apps three times (Debug-Mode, Release-Mode, App-Package) and we don’t have a lot of mysterious surprises which cost us a lot of time.

-Damir


Von: MMalikKhan [mailto:notifications@github.com]
Gesendet: Freitag, 18. November 2016 08:29
An: aspnet/EntityFramework <EntityFramework@noreply.github.com>
Cc: Damir Lisak <damir.lisak@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [aspnet/EntityFramework] .NET Native: optimize code + native toolchain causes runtime exceptions (#6253)


@DamirLisak<https://github.com/DamirLisak>, @natemcmaster<https://github.com/natemcmaster> @MattWhilden<https://github.com/MattWhilden> @jspuij<https://github.com/jspuij> do you have any idea if this is fixed in the Visual Studio 2017 RC ? I am having the same issue if i turn off optimization then i see other null exceptions from different part of the solution. And the worst is the package size is increased x 6 times. any help is much appreciated.

Note: I am using EF 1 Core in my solution.

Thank You

**Comment by jspuij** [comment]
Sadly I don't, our project has been delivered and is in bug fixing phase now. It might be extended in the future using Xamarin.NET. For another project we're using React Native. Funny thing is with the JIT compilation of the current javascript engines and things like instant reloading, developing suddenly is a productivity spree again. Don't need fancy relational storage for that project though.

**Comment by MMalikKhan** [comment]
@DamirLisak  @jspuij thanks so much for your reply, i did try to build the package using Visual Studio 2017 RC and had the same issue with ARM devices. Then, i updated the Default.rd.xml to exclude EntityFrameworkCore libraries and build the package again with 2017RC and this time it did work on ARM devices. I am using below version at the moment.  I hope this help someone, now what i am not sure is .. if i use Visual Studio 2015 Update 3 and add exclude EntityFrameworkCore libraries and build the package then if it still works.
I might try that if possible update so that someone else dont have to learn the hard way.

Dont talk about how my life have been in the last one year after starting a new app using UWP. i spend majority of issues related to platform then my actual code. To spice things up our project uses tempalte10 another microsoft open sourced UI framework, which has so many crash issues, 

"Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },

**Comment by DamirLisak** [comment]
I’m sorry, I didn’t explained it precisely enough:

Excluding the EF-Core libraries with the default.rd.xml worked also in my app, so that I was able to launch my app.
But I had problems in some cases with the DB-Context when I added and saved new objects in the Release-Version.
In Debug-mode it worked as expected.
I tested it with 1.1.0-preview1-final, 1.0.1 and 1.0.0 and all had this same problem. (As far as I can remember it had something to do with reflection)
So, please test all your queries, inserts and updates before you deploy it to the store.
Maybe the the final version 1.1.0 doesn’t has this problem.

Thank you for your information, that 2017 RC also have this old compiler „on-board“.


Von: MMalikKhan [mailto:notifications@github.com]
Gesendet: Dienstag, 22. November 2016 00:04
An: aspnet/EntityFramework <EntityFramework@noreply.github.com>
Cc: Damir Lisak <damir.lisak@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [aspnet/EntityFramework] .NET Native: optimize code + native toolchain causes runtime exceptions (#6253)


@DamirLisak<https://github.com/DamirLisak> @jspuij<https://github.com/jspuij> thanks so much for your reply, i did try to build the package using Visual Studio 2017 RC and had the same issue with ARM devices. Then, i updated the Default.rd.xml to exclude EntityFrameworkCore libraries and build the package again with 2017RC and this time it did work on ARM devices. I am using below version at the moment. I hope this help someone, now what i am not sure is .. if i use Visual Studio 2015 Update 3 and add exclude EntityFrameworkCore libraries and build the package then if it still works.
I might try that if possible update so that someone else dont have to learn the hard way.

Dont talk about how my life have been in the last one year after starting a new app using UWP. i spend majority of issues related to platform then my actual code. To spice things up our project uses tempalte10 another microsoft open sourced UI framework, which has so many crash issues,

"Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
"Microsoft.EntityFrameworkCore.Tools": {
"version": "1.0.0-preview2-final",
"type": "build"
},

**Comment by RonFrick** [comment]
I second that...test now and don't wait until the project is done. I'm still having issues as well in release only. The first problem is on the initial connection, it always throws a null reference error, but I wrote goofy code to handle it and moved on. The other problems included performance on certain queries, so I ended up using SQLite-net as mention by Eric earlier. It is very fast! Thanks again for that Eric, it pretty much saved my project. But it was only a few queries so I was able to still use the parts of EF that are exceptional, like creating the DB, migrating changes, CUD etc. I've had it out in the store for a few months now and so far so good. I'm looking forward to hearing about work on Xamarin compatibility since we plan to move in that direction. Good luck to anyone who got as far as I did before realizing release build are a whole new animal, oh and be prepared to wait while narrowing down what the heck is going on. :) Cheers to all the hard work! I do appreciate it.

**Comment by NPadrutt** [comment]
Can someone post the entries he / she made to make it work?

I tried with this two without success..
```
    <Assembly Name="Microsoft.EntityFrameworkCore" DoNotOptimize="true" DoNotInline="true" />
    <Assembly Name="Microsoft.EntityFrameworkCore.Sqlite" DoNotOptimize="true" DoNotInline="true" />
```
Also I have this issue on x86 not on ARM. Is this still the same issue or something different?

**Comment by jspuij** [comment]
Funny how this bites you, after some minor updates to our app, (updated to EF Core 1.1.0, MSData.SqlLite 1.1.0 and reactiveUI 7.0 stable release, improved sharepoint sync and a version number in the splash screen), it crashes on several places with NullReferenceExceptions and ArgumentNullExceptions. Back to square one :-(

**Comment by MMalikKhan** [comment]
@NPadrutt  which version of EF core are you using ?  i have tested this version and it was all working with those two lines.. 

"Microsoft.EntityFrameworkCore.Sqlite": "1.0.1",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.2",

I did updated to latest 1.1.0 stable version, i am not sure still if this version has any crash issues .. can someone please suggest are you guys @jspuij  @NPadrutt  having issues with "Microsoft.EntityFrameworkCore.Sqlite": "1.1.0" ? is so then i will roll it back , i have not tested this with the store build or compiled released build.

**Comment by NPadrutt** [comment]
@MMalikKhan  I am on 1.1. Interestingly I found something who made it work on my PC in Release. I will now test if it works when I deploy it via the store on my beta flight on my pc and my phone.
Otherwise I'll revert back to 1.0. I tried to avoid this so far since I assume this could cause other issues.. 

What confused me, was that the issues occured as well with the VS2017 RC and updated NetCore Universal Platform. I thought the issue will be fixed there?

**Comment by MMalikKhan** [comment]
@NPadrutt [comments](https://github.com/aspnet/EntityFramework/issues/6253#issuecomment-262095720) if you check the above comments, i also tried with VS2017RC and it did not work. But those two lines to exclude the library from compression did the trick both on VS2017 and VS2015.  Anyway, could you please let me know if you notice any issues on 1.1.0 v? I am still testing in debug/release mode on the PC and phone .. but if you read above comments you can understand this does not give any guarantee that it will work in the store build.  I am not sure why Release build done through the VSStudio and MSbuild has different behavior. So, please test in the store package and let me know if you notice any crash.

**Comment by NPadrutt** [comment]
@MMalikKhan The positive is that I seems to work on my pc now even when installed via store through my beta flight. Bad news is, that it doesn't work on the phone, but I currently doesn't have the two lines added. I will try this tomorrow and report again.

In case someone looks for a similar issue: the change who fixed it for me on the PC was to remove this line from the csproj (or to put it on true):
`<UseDotNetNativeSharedAssemblyFrameworkPackage>false</UseDotNetNativeSharedAssemblyFrameworkPackage>
`

**Comment by NPadrutt** [comment]
@MMalikKhan it seems to work on my phone as well. the only issue I have now is that it takes to long to load and there fore sometimes crashes because of a too long loading. time.. ^^

**Comment by MMalikKhan** [comment]
@NPadrutt Thanks for your update.. Is it **OK** to say that, there are no crash issues with the latest stable version of EF 1.1.0 if you add those two lines to remove compression of SQL libraries?

**Comment by NPadrutt** [comment]
@MMalikKhan  so far, yes. the biggest issue is the performance. But I hope that I can work around this.
I added these three lines as well:

```
    <Assembly Name="System.Nullable{T}" DoNotInline="true" DoNotOptimize="true" />
    <Assembly Name="System.Collections.Generic.List{T}" Dynamic="Required All" />
    <Assembly Name="System.Collections.Generic.IEnumerator{T}" Dynamic="Required All" />
```

I read in a github issue that this can help with the performance. But not sure how accurate that this is. I will make some tests with it in the coming days.

Also I will now test if it works on android with Xamarin as well.

**Comment by DamirLisak** [comment]
@NPadrutt, I also had this problem with the long loading time. First I tried to delegate the initialization of the DbContext to a background thread ( .Migrate()-Method +some other queries on the DBContext) but this is not possible with EF-Core. I don't know why, but it's only possible in the Main-Thread. Maybe @natemcmaster  can explain this. Therefore I use the SplashScreen (https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SplashScreen) for Initializing the Database. It's important that you **subscribe the Dismissed-Event and delegate your code to the Dispatcher**:

```
    public sealed partial class ExtendedSplash : Page
    {
        internal bool dismissed = false; // Variable to track splash screen dismissal status.
        internal Frame rootFrame;

        private SplashScreen splash; // Variable to hold the splash screen object.

        public ExtendedSplash(SplashScreen splashscreen, bool loadState)
        {
            InitializeComponent();
            splash = splashscreen;

            if (splash != null)
            {
                // Register an event handler to be executed when the splash screen has been dismissed.
                splash.Dismissed += new TypedEventHandler<SplashScreen, Object>(DismissedEventHandler);

            }

            // Create a Frame to act as the navigation context
            rootFrame = new Frame();
        }


        // Include code to be executed when the system has transitioned from the splash screen to the extended splash screen (application's first view).
        void DismissedEventHandler(SplashScreen sender, object e)
        {
            // Navigate away from the app's extended splash screen after completing setup operations here...
            if (!dismissed)
            {
                dismissed = true;
                var task = Dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
                {
                    await App.InitializeDB();
                    App.AppInstance.ShowMainWindow();
                });
            }

        }
    }
```
Since I use the SpashScreen I never had any crash during the Launch-phase on ARM-Processors.

**Comment by NPadrutt** [comment]
@DamirLisak Thank you for your code example! that was exactly what I was planning to do :)

**Comment by NPadrutt** [comment]
@MMalikKhan unfortunantely I still get some crashes when compiled with release configuration. I'll try it now with an older version.

**Comment by MMalikKhan** [comment]
@NPadrutt thanks for the update, when i tried to compile with the latest version in release build on ARM, i was getting dependencies missing and the app get installed but dont launch. I am not sure what dependency.. I rolled back to the last stable version which i used on my project.. EF v1.0.1 and it did work this time, however while generating migration this time.. i have been forced to include EF.Design library as well.. the migration was keep giving error "Microsoft.EntityFrameworkCore.Design": "1.0.1", Anyway after i added this from nuget the migration did work, i am not sure why i have to add this when i didnt do any changes to my packages .. the last time i added some migrations i only had tooling and EF core library.. i am very positive nothing changed on my project.. but this time it forced me to add Design library well.. may be @natemcmaster  might have clue .. I am still testing the build in release mode .. and making sure i didnt break something ..

**Comment by DamirLisak** [comment]
The bug is still present!
I have tested my App with the latest compiler of Microsoft Visual Studio Community 2017 RC Version 15.0.26127.0 D15REL.
Excluding the Entity-Framework-Assemblies in the runtime directives (rd.xml) works now.

@natemcmaster : Will Microsoft Support ARM-Processors (Phone) in the future or is it dead and gone?

Here is the Stack-Trace:

```
Unhandled exception at 0x681A8433 (mrt100_app.dll) in HandballReporter.uwp.exe: 0xC0000005: Access violation reading location 0x00000001. 

 	[Externer Code]	
 	System.Private.CoreLib.dll!System.Array<T>.GetEnumerator() Zeile 2459	C#
 	System.Linq.dll!System.Linq.Enumerable.UnionIterator<TSource>(System.Collections.Generic.IEnumerable<TSource> first, System.Collections.Generic.IEnumerable<TSource> second, System.Collections.Generic.IEqualityComparer<TSource> comparer)	C#
 	System.Linq.dll!System.Linq.Enumerable.WhereEnumerableIterator<System.Type>.MoveNext() Zeile 196	C#
 	System.Collections.dll!System.Collections.Generic.List<System.Type>.List(System.Collections.Generic.IEnumerable<System.Type> collection) Zeile 90	C#
 	Microsoft.EntityFrameworkCore.Relational.dll!System.SharedTypeExtensions.TryGetElementType(System.Type type, System.Type interfaceOrBaseType)	Unbekannt
 	Microsoft.EntityFrameworkCore.Relational.dll!System.Reflection.PropertyInfoExtensions.FindCandidateNavigationPropertyType(System.Reflection.PropertyInfo propertyInfo, System.Func<System.Type, bool> isPrimitiveProperty)	Unbekannt
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationalForeignKeyAttributeConvention.FindCandidateNavigationPropertyType(System.Reflection.PropertyInfo propertyInfo)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.FindForeignKeyAttributeOnProperty(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType, string navigationName)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyAttributeConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnForeignKeyAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder principalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder dependentEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> dependentProperties, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> principalProperties, bool? isUnique, bool? isRequired, Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior? deleteBehavior, bool removeCurrent, bool oldRelationshipInverted, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? principalEndConfigurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, bool runConventions, System.Collections.Generic.List<System.Tuple<Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, string, System.Reflection.PropertyInfo>> removedNavigations, System.Collections.Generic.List<System.Tuple<Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey>> removedForeignKeys)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder principalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder dependentEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> dependentProperties, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> principalProperties, bool? isUnique, bool? isRequired, Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior? deleteBehavior, bool removeCurrent, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? principalEndConfigurationSource, bool oldRelationshipInverted, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> properties, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType dependentEntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> properties, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType dependentEntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> properties, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ForeignKeyPropertyDiscoveryConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPrincipalEndSet(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder relationshipBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder principalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder dependentEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> dependentProperties, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> principalProperties, bool? isUnique, bool? isRequired, Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior? deleteBehavior, bool removeCurrent, bool oldRelationshipInverted, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? principalEndConfigurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, bool runConventions, System.Collections.Generic.List<System.Tuple<Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, string, System.Reflection.PropertyInfo>> removedNavigations, System.Collections.Generic.List<System.Tuple<Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.ForeignKey>> removedForeignKeys)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder principalEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder dependentEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> dependentProperties, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Internal.Property> principalProperties, bool? isUnique, bool? isRequired, Microsoft.EntityFrameworkCore.Metadata.DeleteBehavior? deleteBehavior, bool removeCurrent, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? principalEndConfigurationSource, bool oldRelationshipInverted, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType principalEntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType dependentEntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType principalEntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType dependentEntityType, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToPrincipal, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToDependent, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource? configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.Navigations(string navigationToPrincipalName, string navigationToDependentName, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder targetEntityTypeBuilder, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? navigationToTarget, Microsoft.EntityFrameworkCore.Metadata.Internal.PropertyIdentity? inverseNavigation, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Relationship(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder targetEntityTypeBuilder, string navigationToTargetName, string inverseNavigationName, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.CreateRelationships(System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.RelationshipCandidate> relationshipCandidates, Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAdded(Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder entityTypeBuilder)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(Microsoft.EntityFrameworkCore.Metadata.Internal.EntityType entityType, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(System.Type type, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(System.Type type, Microsoft.EntityFrameworkCore.Metadata.Internal.ConfigurationSource configurationSource, bool runConventions)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.ModelBuilder.Entity(System.Type type)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.FindSets(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder, Microsoft.EntityFrameworkCore.DbContext context)	Unbekannt
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.Internal.RelationalModelSource.FindSets(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder, Microsoft.EntityFrameworkCore.DbContext context)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(Microsoft.EntityFrameworkCore.DbContext context, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.EntityFrameworkCore.Internal.IModelValidator validator)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel.AnonymousMethod__0(object k)	Unbekannt
 	System.Collections.Concurrent.dll!System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, System.Func<TKey, TValue> valueFactory)	C#
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(Microsoft.EntityFrameworkCore.DbContext context, Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.IConventionSetBuilder conventionSetBuilder, Microsoft.EntityFrameworkCore.Internal.IModelValidator validator)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.LazyRef<Microsoft.EntityFrameworkCore.Metadata.IModel>.Value.get()	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Internal.DbContextServices.Model.get()	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.AddEntityFramework.AnonymousMethod__0_6(System.IServiceProvider p)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService factoryService, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator>(System.IServiceProvider provider)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService<System.__Canon>()	Unbekannt
 	Microsoft.EntityFrameworkCore.Sqlite.dll!Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseProviderServices.RelationalDatabaseCreator.get()	Unbekannt
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseProviderServices.Creator.get()	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.AddEntityFramework.AnonymousMethod__0_13(System.IServiceProvider p)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService factoryService, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider provider, System.Type serviceType)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Microsoft.EntityFrameworkCore.Migrations.Internal.SqliteHistoryRepository>(System.IServiceProvider provider)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService<System.__Canon>()	Unbekannt
 	Microsoft.EntityFrameworkCore.Sqlite.dll!Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseProviderServices.HistoryRepository.get()	Unbekannt
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.Infrastructure.RelationalServiceCollectionExtensions.AddRelational.AnonymousMethod__0_8(System.IServiceProvider p)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService factoryService, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.RealizeService.AnonymousMethod__0(Microsoft.Extensions.DependencyInjection.ServiceProvider provider)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.dll!Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type serviceType)	Unbekannt
 	Microsoft.Extensions.DependencyInjection.Abstractions.dll!Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService<Microsoft.EntityFrameworkCore.Migrations.IMigrator>(System.IServiceProvider provider)	Unbekannt
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService<Microsoft.EntityFrameworkCore.Migrations.IMigrator>(Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider> accessor)	Unbekannt
 	Microsoft.EntityFrameworkCore.Relational.dll!Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade databaseFacade)	Unbekannt
>	HandballReporter.uwp.exe!HandballReporter.uwp.App.InitializeDB() Zeile 166	C#
 	HandballReporter.uwp.exe!HandballReporter.uwp.Views.ExtendedSplash.DismissedEventHandler.AnonymousMethod__4_0() Zeile 46	C#


```

**Comment by natemcmaster** [comment]
@DamirLisak I'm not aware of any progress in this bug. @MattWhilden can you share a status update if there is one?

**Comment by richardcastle** [comment]
I've just installed the latest Visual Studio 2017 RC update (8th Feb 2017) and rebuilt and targeted Release mode to ARM and the app deploys and launches. It seems this has been fixed in the latest update. Hurrrah!

**Comment by rowanmiller** [comment]
Closing as we believe this is all fixed in the latest release (VS2017 RC). Please open a new issue if there are specific cases that are not fixed.

**Comment by DamirLisak** [comment]
Unfortunately it's **NOT FIXED**!
@richardcastle : How did you test it? Do you have simple database-model?  

I reopened this issue at [https://github.com/aspnet/EntityFramework/issues/7597](https://github.com/aspnet/EntityFramework/issues/7597)

**Comment by richardcastle** [comment]
@DamirLisak I performed the VS2017 update released last week. Removed the .RD optimisation exclusions which I had to put in to allow the release mode to work, build and now my app launches on my Lumia 950. Previously the app would crash and return to the app list on the phone during startup. Exception was normally at Migrate. The database is relatively complicated with about 10 tables with relationships between most of them. So clearly there have been fixed added, but perhaps there are some edge cases remaining?

**Comment by richardcastle** [comment]
OK. Was working the code tonight, made some minor non-DB changes and it's not working again. I suspect I got lucky. I've tried a couple of further rebuilds and still not working. @rowanmiller it seems we should reopen this thread unfortunately.

**Comment by divega** [comment]
@richardcastle given that it is hard to tell if the failure you are seeing has the same root cause, could you please create a new issue and provide a repro project?

**Comment by DamirLisak** [comment]
My Problem is solved now. 
I used **Microsoft.NETCore.UniversalWindowsPlatform** 5.2.2 instead of **5.3.0**.
See [https://github.com/aspnet/EntityFramework/issues/7597](https://github.com/aspnet/EntityFramework/issues/7597)

**Comment by richardcastle** [comment]
OK. There are some updates on issue #7597 with the suggestion that it was the Microsoft.NETCore.UniversalWindowsPlatform needed to be updated to 5.3. This appears to have solved the issue for me.
