### ISSUE TITLE
StackOverflowException with InversePropertyAttribute on 1.1.0

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#7057]
Reported over email...

> I build a taxi service app with backend on ASP.NET Core.
In order to use latest SignalR I switched all package references to 1.2.0-* as it is defined in a SignalR repository. But as I try to perform any request to a database I receive StackOverflowException

I have the repro project for this (it couldn't be shared publically), so I can give it to whoever investigates.

Attaching stack trace as it is too big to add inline [StackTrace.txt](https://github.com/aspnet/EntityFramework/files/600818/StackTrace.txt)

**Comment by xperiandri** [comment]
This issue only appeared in 1.2
In 1.0 it worked, 1.1 I did not check.
My guess is that because of inheritance and cross dependencies

**Comment by divega** [comment]
@AndriySvyryd please check if this was regressed in 1.1.

**Comment by xperiandri** [comment]
Switch everything to 1.1.0-* ?

**Comment by xperiandri** [comment]
So I commented out all the navigation attributes except in `CarRequest`
``` C#
        [ForeignKey("AcceptedResponseId")]
        public CarResponse AcceptedCarResponse { get; set; }

        //[ForeignKey(nameof(PassengerId))]
        //[InverseProperty(nameof(HahaTaxi.Entities.Passenger.CarRequests))]
        public virtual Passenger Passenger { get; set; }

        [InverseProperty(nameof(CarResponse.Request))]
        public virtual ICollection<CarResponse> CarResponses { get; set; }
```

**Comment by AndriySvyryd** [comment]
Verified that the regression was in 1.1.0

**Comment by AndriySvyryd** [comment]
Fixed in cb79bb8

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by TheGatsby81** [comment]
I'm still seeing a problem with the latest build here (1.2.0-preview1-24047). ForeignKey attribute does not work with a nullable key.

> InvalidOperationException: Unable to determine the relationship represented by navigation property 'BaseTable.ReferencedTable' of type 'ReferencedTable'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

> Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
