### ISSUE TITLE
Exception when setting the default value for a nullable int field

### ISSUE THREAD

**Issue by TomWilloughby** [aspnet/EntityFramework#8015]
**Describe what is not working as expected.**
In a `DBContext` `OnModelCreating()` method, setting a default value on a nullable int field using `HasDefaultValue( null )` throws an exception, while using `HasDefaultValueSql( "null" )` works as expected. The exception message is confusing and potentially inaccurate, suggesting that two identity columns have been defined as opposed to suggesting that there is an issue with the default value. This might be because Entity Framework Core is assuming that any int field with a null default value must be an identity or auto-incrementing column.
```
Exception message:
Multiple identity columns specified for table 'Test'. Only one identity column per table is allowed.

Stack trace:
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at efcore_default_null_bug.Program.Main(String[] args) in A:\ghp\default-null-bug\efcore-default-null-bug\src\efcore-default-null-bug\Program.cs:line 46
```

### Steps to reproduce
Complete reproduction code is available at https://github.com/TomWilloughby/efcore-default-null-bug-reproduction . Just clone, put a connection string in appsettings.json, and run. There is also additional instructions in the project readme that detail reproducing the bug from scratch.

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 1.1.1
Operating system:  Windows 10 Pro
IDE: Visual Studio 2015 Update 3

If any more information is required, I would be happy to provide it.

**Comment by smitpatel** [comment]
Note for Triage: Related to #7872

**Comment by TomWilloughby** [comment]
Please correct me if I've missed something, but I don't think this issue is related to #7872 . That deals with when the database is set up to apply a default value outside of Entity Framework, and this is about the difference in behaviour of `HasDefaultValue( null )` for ints compared to other data types (and the confusing message it generates).

**Comment by ajcvickers** [comment]
@TomWilloughby I don't think @smitpatel is saying these are the same issue, but rather we have been discussing the behaviors of HasDefaultValue in that issue, with one decision being that calling HasDefaultValue() (i.e. with no argument) will set the default value to null, which is interestingly what you are trying to do but its not working. So the items are related, but not the same.

**Comment by ajcvickers** [comment]
@TomWilloughby We discussed this in triage and have a follow up question: what is it that you want to achieve by setting the default value to null? Given that this is the default anyway when a column doesn't have any default constraint, will it not always result in the same behavior?

**Comment by TomWilloughby** [comment]
I'm trying to write self-documenting code. By declaring it explicitly, another developer can glance at it and see what the behaviours are without having to know anything about the underlying framework or storage technology.

The main reason I created this issue, though, was simply the inconsistency. Since using the method in that way works on a boolean and a string field, I expected it to act the same on an int field.

**Comment by AndriySvyryd** [comment]
This was fixed in c9c960041ab2944497b3c62949de5b61c67e7165. `HasDefaultValue( null )` now doesn't mark the property as ValueGeneratedOnAdd

**Comment by ajcvickers** [comment]
@AndriySvyryd But if you do this:
```C#
.ValueGeneratedOnAdd()
.HasDefaultValue(null)
```
then it still fails--I have been thinking about how to make this work.
